add iOS Feature - API #37
No-57/orange-frontstage-api pull request #22
Opened 2023-12-12 16:49 UTC by KaoWeiCheng

## add Board and Theme GET API

#### Request:
`GET https://{domainhost}/v1/boards?code={code}&limit={limit}`

`GET https://{domainhost}/v1/themes?{type}`

#### Note
The columns "created_at" and "updated_at" in the DB table "boards" correspond to "created_date" and "updated_date" mentioned in the documentation. 
My program currently prioritizes the table's columns, so if any changes are needed, please let me know. Thank you.

2023-12-13 04:08 UTC, Vince-Ku commented on src/main/java/com/orange/main/Theme/service/impl/ThemeServiceImpl.java
> +        return themeRepository.findByType(type);
What are the consequences of encountering an exception in this context, like DB connection failure or an object mapping failure, In such cases, What exact JSON format will be returned?

2023-12-13 04:09 UTC, Vince-Ku commented on src/main/java/com/orange/main/boards/service/impl/BoardssServiceImpl.java
> +    }
ditto

2023-12-13 04:20 UTC, asdfg429 commented
LGTM
@Vince-Ku your questions will solved after you check issue #15.
But I don't know how to link this issue to #15.
I created an ExceptionHandler.

2023-12-13 14:18 UTC, Vince-Ku commented
> LGTM @Vince-Ku your questions will solved after you check issue #15. But I don't know how to link this issue to #15. I created an ExceptionHandler.

got it.

2023-12-13 14:18 UTC, Vince-Ku approved these changes
LGTM

2023-12-13 15:19 UTC, asdfg429 requested changes
Check comments, please remove annotation.

2023-12-13 15:19 UTC, asdfg429 commented on src/main/java/com/orange/main/Theme/controller/ThemeController.java
> +@RequestMapping("/v1")
Please remove this line. Check #15. I add some code on BaseController like these `@RequestMapping("api/v1")` .
These could make all RestControllers URL started with `api/v1` .

2023-12-13 15:19 UTC, asdfg429 commented on src/main/java/com/orange/main/boards/controller/BoardsController.java
> +@RequestMapping("/v1")
ditto

2023-12-20 04:30 UTC, Vince-Ku commented on src/main/java/com/orange/main/Theme/controller/ThemeController.java
> +@RequestMapping("/v1")
https://github.com/No-57/orange-frontstage-api/pull/22/commits/162cc574fcb5b4d19efcff3810d77cdbf1072a0d

2023-12-20 04:30 UTC, Vince-Ku commented on src/main/java/com/orange/main/boards/controller/BoardsController.java
> +@RequestMapping("/v1")
https://github.com/No-57/orange-frontstage-api/pull/22/commits/162cc574fcb5b4d19efcff3810d77cdbf1072a0d

2023-12-20 04:35 UTC, Vince-Ku commented
@KaoWeiCheng 
I made a few adjustments, please check.

For a quick test, I've rebased this branch onto the latest Main branch, I hope this is ok with you 🥹.

2023-12-20 06:51 UTC, KaoWeiCheng commented
No problem at all, thank you!

2023-12-21 05:19 UTC, merged