add Dockerfile
No-57/orange-frontstage-api pull request #9
Opened 2023-10-28 06:34 UTC by KaoWeiCheng

## add Dockerfile
Use DB_SCHEMA.sql to init schema

### Step1 . build image
`docker build -f Dockerfile -t orange/postgres:16.0 .`

### Step2. run container
`docker run --name postgres_container -p 5432:5432 -v postgres-volume:/var/lib/postgresql/data -d orange/postgres:16.0`

---

### Trace logs to check schema init
`docker logs <container_id>`

---

### Notice
* makesure  tho volume is new, 
if volume is old, the schema will not init

2023-10-28 07:57 UTC, shadow3x3x3 requested changes
Please add `CREATE DATABASE` statement to [DB_SCHEMA.sql](https://github.com/No-57/orange-frontstage-api/blob/main/DB/DB_SCHEMA.sql)

2023-10-28 13:13 UTC, KaoWeiCheng commented
OK add to [DB_SCHEMA.sql](https://github.com/No-57/orange-frontstage-api/blob/main/DB/DB_SCHEMA.sql) finish !

2023-10-28 13:20 UTC, shadow3x3x3 approved these changes

2023-11-05 09:03 UTC, merged

2023-11-06 16:21 UTC, asdfg429 reviewed
push